version: "{build}"

clone_depth: 10

shallow_clone: true

build: off

install:
  - SET PATH=C:\Ruby%ruby_folder_version%\bin;%PATH%

  # Work around slow `gem install` by downloading the gem ourselves
  #- gem install bundler --quiet --no-ri --no-rdoc
  - appveyor DownloadFile https://rubygems.org/downloads/bundler-1.9.1.gem -FileName C:\Ruby%ruby_folder_version%\lib\ruby\gems\%ruby_gems_folder%\cache\bundler-1.9.1.gem
  - gem install --local C:\Ruby%ruby_folder_version%\lib\ruby\gems\%ruby_gems_folder%\cache\bundler-1.9.1.gem --quiet --no-ri --no-rdoc
  - bundle install --clean --retry 3

test_script:
  - ruby --version
  - python --version
  - gem --version
  - bundler --version
  - bash ./script/cibuild

cache:
  - '%USERPROFILE%\.gem -> Gemfile,github-pages.gemspec'
  - C:\Ruby%ruby_folder_version%\bin -> Gemfile,github-pages.gemspec
  - C:\Ruby%ruby_folder_version%\lib\ruby\gems\%ruby_gems_folder% -> Gemfile,github-pages.gemspec

environment:
  matrix:
#    - ruby_folder_version: "193"
#      ruby_gems_folder: "1.9.1"
    - ruby_folder_version: "200"
      ruby_gems_folder: "2.0.0"
    - ruby_folder_version: "21"
      ruby_gems_folder: "2.1.0"
    - ruby_folder_version: "22"
      ruby_gems_folder: "2.2.0"
    - ruby_folder_version: "22-x64"
      ruby_gems_folder: "2.2.0"

matrix:
  fast_finish: true